### PR TITLE
Update autofill to fixed release/identities

### PR DESCRIPTION
**Pull request by jonathanKingston**
Task/Issue URL: https://app.asana.com/0/392891325557410/1201884903028199
Tech Design URL:
CC:

**Description**:

Fixes broken release/identities update

**Steps to test this PR**:
1. Open https://stripe.dev/elements-examples/
2. Ensure autofill is displayed when clicking into the name field

**OS Testing**:

* [ ] iOS 13
* [ ] iOS 14
* [ ] iOS 15
* [ ] macOS 10.15
* [ ] macOS 11

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Review by brindy — APPROVED** [review]
Thanks - I checked the stripe page and netflix and got the autofill prompts. 

After merging please tag BSK and bump the version by 0.0.1

**Review by brindy — CHANGES_REQUESTED** [review]
Sorry - I missed this. It doesn't appear to be a fix on main, but pointing to an arbitrary branch?

This needs to be a fix on main and tagged correctly.  We can have dependencies on unreleased code as it will affect the stability of the app.

**Review by brindy — APPROVED** [review]
As agreed we'll keep pointing to this branch and update it throughout the day.

**Comment by jonathanKingston** [comment]
Closed in favour of: https://github.com/duckduckgo/BrowserServicesKit/pull/67 :)

**Pull request closed without merging**
