### PR TITLE
Add ESLint to BrowserServicesKit

### PR DESCRIPTION
**Pull request by jonathanKingston**
Task/Issue URL:  https://app.asana.com/0/1200194497630846/1201513704898090/f
Tech Design URL:
CC:

**Description**:

**Steps to test this PR**:
1. Modify a .js file
2. Run npx eslint .

Ensure there's errors

**OS Testing**:

* [ ] iOS 13
* [ ] iOS 14
* [ ] iOS 15
* [ ] macOS 10.15
* [ ] macOS 11

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by mallexxx** [comment]
@jonathanKingston which folder this should be run in? I get an error when running in BSK root:
Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load parser '@babel/eslint-parser' declared in 'Resources/duckduckgo-autofill/.eslintrc': Cannot find module '@babel/eslint-parser'

**Comment by jonathanKingston** [comment]
@mallexxx odd the whole 'Resources' directory should be excluded so shouldn't be causing this. I'll take a look later.

**Review by mallexxx — APPROVED** [review]
@jonathanKingston sorry, I've run npm install from within content blocking dir, removed it and purged npm cache and it worked as intended, LGTM

**Comment by brindy** [comment]
@jonathanKingston this appears to be approved but needs to have some conflicts fixed, feel free to merge once sorted. :)

**Comment by jonathanKingston** [comment]
Yeah very very very bit rotted, closing!

This is still worthwhile for our JS scripts here unless we want to lift and shift to C-S-S which would be my preferred even for internals etc.

**Comment by brindy** [comment]
Thanks @jonathanKingston

**Pull request closed without merging**
