### PR TITLE
PixelKit

### PR DESCRIPTION
**Pull request by federicocappelli**
Task/Issue URL: https://app.asana.com/0/1205842942115003/1206999268603553/f
macOS PR: https://github.com/duckduckgo/macos-browser/pull/2656
What kind of version bump will this require?: Minor (new feature)

**Description**:

Migration of PixelKit to BSK and adoption in macOS ONLY

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

### CODE REVIEW

**Comment by jaceklyp** [comment]
Hey, I hope I'm not too late to the party, but could we consider having library called PixelKit (I'm super okay with that) but class named just Pixel (instead of PixelKit)? so we can still use this API as Pixel.fire(pixelname...)?

**Comment by federicocappelli** [comment]
@jaceklyp yes, that's a good idea, I'll modify the name before using the library from BSK

**Comment by federicocappelli** [comment]
@jaceklyp (I deleted my previous comment) actually we may have a problem with that, in iOS the two ways of using pixels will need to coexist for a while, so having the same name would probably be a problem, we'll be able to rename PixelKit after the full migration is completed.

**Comment by jaceklyp** [comment]
Ok, sounds perfect to me if we'd still consider it after migration!

**Pull request closed without merging**
